### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by kasparjarek** [aiven/transforms-for-apache-kafka-connect#81]
There wasn't any release since Apr 28, 2021. What do you think about creating a new release? :)

I would really appreciate it. The new features could be used directly by downloading the package from Github, without the need to build it locally.

**Comment by ivanyu** [comment]
There were also no functional changes, that's why we skipped releases. However, a number of dependency version bumps accumulated over this period is high enough, we need to make a release. There will be one after #82 is merged.

**Comment by TroyCoombs** [comment]
These [PR](https://github.com/aiven/transforms-for-apache-kafka-connect/pull/82#pullrequestreview-1364993035) was merged today.  How long before it's available for use within the Aiven ecosystem?

**Comment by ivanyu** [comment]
The Github release is on the way: #85. It'll become shortly after available on Aiven

**Comment by kasparjarek** [comment]
[Release 1.4.0](https://github.com/aiven/transforms-for-apache-kafka-connect/releases/tag/v1.4.0) is out. Thank you. I am closing the issue.
