### ISSUE TITLE
New connector ExtractTopicFromValueSchema

### ISSUE THREAD

**Issue by mikaka-paf** [aiven/transforms-for-apache-kafka-connect#94]
We would need to have same kind of functionality as the ExtractTopic have, but would want to take the schema name value and use that as a Topic name. I have already created PR:

https://github.com/aiven/transforms-for-apache-kafka-connect/pull/93  

where I have implementation for review. Could you please check that out.

**Comment by AnatolyPopov** [comment]
Should be addressed by this https://github.com/aiven/transforms-for-apache-kafka-connect/pull/93
